#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUR_Integer_WAPRO.Modules.Database.Services
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WFMAG")]
	public partial class TablesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKONTRAHENT(KONTRAHENT instance);
    partial void UpdateKONTRAHENT(KONTRAHENT instance);
    partial void DeleteKONTRAHENT(KONTRAHENT instance);
    partial void InsertARTYKUL(ARTYKUL instance);
    partial void UpdateARTYKUL(ARTYKUL instance);
    partial void DeleteARTYKUL(ARTYKUL instance);
    partial void InsertDOKUMENT_MAGAZYNOWY(DOKUMENT_MAGAZYNOWY instance);
    partial void UpdateDOKUMENT_MAGAZYNOWY(DOKUMENT_MAGAZYNOWY instance);
    partial void DeleteDOKUMENT_MAGAZYNOWY(DOKUMENT_MAGAZYNOWY instance);
    #endregion
		
		public TablesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TablesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TablesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TablesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KONTRAHENT> KONTRAHENTs
		{
			get
			{
				return this.GetTable<KONTRAHENT>();
			}
		}
		
		public System.Data.Linq.Table<ARTYKUL> ARTYKULs
		{
			get
			{
				return this.GetTable<ARTYKUL>();
			}
		}
		
		public System.Data.Linq.Table<DOKUMENT_MAGAZYNOWY> DOKUMENT_MAGAZYNOWies
		{
			get
			{
				return this.GetTable<DOKUMENT_MAGAZYNOWY>();
			}
		}
		
		public System.Data.Linq.Table<POZYCJA_DOKUMENTU_MAGAZYNOWEGO> POZYCJA_DOKUMENTU_MAGAZYNOWEGOs
		{
			get
			{
				return this.GetTable<POZYCJA_DOKUMENTU_MAGAZYNOWEGO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KONTRAHENT")]
	public partial class KONTRAHENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID_KONTRAHENTA;
		
		private string _NAZWA;
		
		private string _NAZWA_PELNA;
		
		private string _NIP;
		
		private string _KOD_POCZTOWY;
		
		private string _MIEJSCOWOSC;
		
		private string _ULICA_LOKAL;
		
		private System.DateTime _LAST_MODIFIED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KONTRAHENTAChanging(decimal value);
    partial void OnID_KONTRAHENTAChanged();
    partial void OnNAZWAChanging(string value);
    partial void OnNAZWAChanged();
    partial void OnNAZWA_PELNAChanging(string value);
    partial void OnNAZWA_PELNAChanged();
    partial void OnNIPChanging(string value);
    partial void OnNIPChanged();
    partial void OnKOD_POCZTOWYChanging(string value);
    partial void OnKOD_POCZTOWYChanged();
    partial void OnMIEJSCOWOSCChanging(string value);
    partial void OnMIEJSCOWOSCChanged();
    partial void OnULICA_LOKALChanging(string value);
    partial void OnULICA_LOKALChanged();
    partial void OnLAST_MODIFIEDChanging(System.DateTime value);
    partial void OnLAST_MODIFIEDChanged();
    #endregion
		
		public KONTRAHENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KONTRAHENTA", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal ID_KONTRAHENTA
		{
			get
			{
				return this._ID_KONTRAHENTA;
			}
			set
			{
				if ((this._ID_KONTRAHENTA != value))
				{
					this.OnID_KONTRAHENTAChanging(value);
					this.SendPropertyChanging();
					this._ID_KONTRAHENTA = value;
					this.SendPropertyChanged("ID_KONTRAHENTA");
					this.OnID_KONTRAHENTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAZWA", DbType="VarChar(50)")]
		public string NAZWA
		{
			get
			{
				return this._NAZWA;
			}
			set
			{
				if ((this._NAZWA != value))
				{
					this.OnNAZWAChanging(value);
					this.SendPropertyChanging();
					this._NAZWA = value;
					this.SendPropertyChanged("NAZWA");
					this.OnNAZWAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAZWA_PELNA", DbType="VarChar(200)")]
		public string NAZWA_PELNA
		{
			get
			{
				return this._NAZWA_PELNA;
			}
			set
			{
				if ((this._NAZWA_PELNA != value))
				{
					this.OnNAZWA_PELNAChanging(value);
					this.SendPropertyChanging();
					this._NAZWA_PELNA = value;
					this.SendPropertyChanged("NAZWA_PELNA");
					this.OnNAZWA_PELNAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIP", DbType="VarChar(30)")]
		public string NIP
		{
			get
			{
				return this._NIP;
			}
			set
			{
				if ((this._NIP != value))
				{
					this.OnNIPChanging(value);
					this.SendPropertyChanging();
					this._NIP = value;
					this.SendPropertyChanged("NIP");
					this.OnNIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOD_POCZTOWY", DbType="VarChar(20)")]
		public string KOD_POCZTOWY
		{
			get
			{
				return this._KOD_POCZTOWY;
			}
			set
			{
				if ((this._KOD_POCZTOWY != value))
				{
					this.OnKOD_POCZTOWYChanging(value);
					this.SendPropertyChanging();
					this._KOD_POCZTOWY = value;
					this.SendPropertyChanged("KOD_POCZTOWY");
					this.OnKOD_POCZTOWYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIEJSCOWOSC", DbType="VarChar(50)")]
		public string MIEJSCOWOSC
		{
			get
			{
				return this._MIEJSCOWOSC;
			}
			set
			{
				if ((this._MIEJSCOWOSC != value))
				{
					this.OnMIEJSCOWOSCChanging(value);
					this.SendPropertyChanging();
					this._MIEJSCOWOSC = value;
					this.SendPropertyChanged("MIEJSCOWOSC");
					this.OnMIEJSCOWOSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULICA_LOKAL", DbType="VarChar(50)")]
		public string ULICA_LOKAL
		{
			get
			{
				return this._ULICA_LOKAL;
			}
			set
			{
				if ((this._ULICA_LOKAL != value))
				{
					this.OnULICA_LOKALChanging(value);
					this.SendPropertyChanging();
					this._ULICA_LOKAL = value;
					this.SendPropertyChanged("ULICA_LOKAL");
					this.OnULICA_LOKALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MODIFIED", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_MODIFIED
		{
			get
			{
				return this._LAST_MODIFIED;
			}
			set
			{
				if ((this._LAST_MODIFIED != value))
				{
					this.OnLAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._LAST_MODIFIED = value;
					this.SendPropertyChanged("LAST_MODIFIED");
					this.OnLAST_MODIFIEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ARTYKUL")]
	public partial class ARTYKUL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID_ARTYKULU;
		
		private string _NAZWA;
		
		private string _NAZWA_ORYG;
		
		private string _NAZWA2;
		
		private string _INDEKS_KATALOGOWY;
		
		private string _INDEKS_HANDLOWY;
		
		private string _KOD_KRESKOWY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ARTYKULUChanging(decimal value);
    partial void OnID_ARTYKULUChanged();
    partial void OnNAZWAChanging(string value);
    partial void OnNAZWAChanged();
    partial void OnNAZWA_ORYGChanging(string value);
    partial void OnNAZWA_ORYGChanged();
    partial void OnNAZWA2Changing(string value);
    partial void OnNAZWA2Changed();
    partial void OnINDEKS_KATALOGOWYChanging(string value);
    partial void OnINDEKS_KATALOGOWYChanged();
    partial void OnINDEKS_HANDLOWYChanging(string value);
    partial void OnINDEKS_HANDLOWYChanged();
    partial void OnKOD_KRESKOWYChanging(string value);
    partial void OnKOD_KRESKOWYChanged();
    #endregion
		
		public ARTYKUL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ARTYKULU", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal ID_ARTYKULU
		{
			get
			{
				return this._ID_ARTYKULU;
			}
			set
			{
				if ((this._ID_ARTYKULU != value))
				{
					this.OnID_ARTYKULUChanging(value);
					this.SendPropertyChanging();
					this._ID_ARTYKULU = value;
					this.SendPropertyChanged("ID_ARTYKULU");
					this.OnID_ARTYKULUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAZWA", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string NAZWA
		{
			get
			{
				return this._NAZWA;
			}
			set
			{
				if ((this._NAZWA != value))
				{
					this.OnNAZWAChanging(value);
					this.SendPropertyChanging();
					this._NAZWA = value;
					this.SendPropertyChanged("NAZWA");
					this.OnNAZWAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAZWA_ORYG", DbType="VarChar(40)")]
		public string NAZWA_ORYG
		{
			get
			{
				return this._NAZWA_ORYG;
			}
			set
			{
				if ((this._NAZWA_ORYG != value))
				{
					this.OnNAZWA_ORYGChanging(value);
					this.SendPropertyChanging();
					this._NAZWA_ORYG = value;
					this.SendPropertyChanged("NAZWA_ORYG");
					this.OnNAZWA_ORYGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAZWA2", DbType="VarChar(40)")]
		public string NAZWA2
		{
			get
			{
				return this._NAZWA2;
			}
			set
			{
				if ((this._NAZWA2 != value))
				{
					this.OnNAZWA2Changing(value);
					this.SendPropertyChanging();
					this._NAZWA2 = value;
					this.SendPropertyChanged("NAZWA2");
					this.OnNAZWA2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDEKS_KATALOGOWY", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string INDEKS_KATALOGOWY
		{
			get
			{
				return this._INDEKS_KATALOGOWY;
			}
			set
			{
				if ((this._INDEKS_KATALOGOWY != value))
				{
					this.OnINDEKS_KATALOGOWYChanging(value);
					this.SendPropertyChanging();
					this._INDEKS_KATALOGOWY = value;
					this.SendPropertyChanged("INDEKS_KATALOGOWY");
					this.OnINDEKS_KATALOGOWYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDEKS_HANDLOWY", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string INDEKS_HANDLOWY
		{
			get
			{
				return this._INDEKS_HANDLOWY;
			}
			set
			{
				if ((this._INDEKS_HANDLOWY != value))
				{
					this.OnINDEKS_HANDLOWYChanging(value);
					this.SendPropertyChanging();
					this._INDEKS_HANDLOWY = value;
					this.SendPropertyChanged("INDEKS_HANDLOWY");
					this.OnINDEKS_HANDLOWYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOD_KRESKOWY", DbType="VarChar(20)")]
		public string KOD_KRESKOWY
		{
			get
			{
				return this._KOD_KRESKOWY;
			}
			set
			{
				if ((this._KOD_KRESKOWY != value))
				{
					this.OnKOD_KRESKOWYChanging(value);
					this.SendPropertyChanging();
					this._KOD_KRESKOWY = value;
					this.SendPropertyChanged("KOD_KRESKOWY");
					this.OnKOD_KRESKOWYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOKUMENT_MAGAZYNOWY")]
	public partial class DOKUMENT_MAGAZYNOWY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID_DOK_MAGAZYNOWEGO;
		
		private System.Nullable<decimal> _ID_KONTRAHENTA;
		
		private string _RODZAJ_DOKUMENTU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DOK_MAGAZYNOWEGOChanging(decimal value);
    partial void OnID_DOK_MAGAZYNOWEGOChanged();
    partial void OnID_KONTRAHENTAChanging(System.Nullable<decimal> value);
    partial void OnID_KONTRAHENTAChanged();
    partial void OnRODZAJ_DOKUMENTUChanging(string value);
    partial void OnRODZAJ_DOKUMENTUChanged();
    #endregion
		
		public DOKUMENT_MAGAZYNOWY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOK_MAGAZYNOWEGO", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal ID_DOK_MAGAZYNOWEGO
		{
			get
			{
				return this._ID_DOK_MAGAZYNOWEGO;
			}
			set
			{
				if ((this._ID_DOK_MAGAZYNOWEGO != value))
				{
					this.OnID_DOK_MAGAZYNOWEGOChanging(value);
					this.SendPropertyChanging();
					this._ID_DOK_MAGAZYNOWEGO = value;
					this.SendPropertyChanged("ID_DOK_MAGAZYNOWEGO");
					this.OnID_DOK_MAGAZYNOWEGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KONTRAHENTA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID_KONTRAHENTA
		{
			get
			{
				return this._ID_KONTRAHENTA;
			}
			set
			{
				if ((this._ID_KONTRAHENTA != value))
				{
					this.OnID_KONTRAHENTAChanging(value);
					this.SendPropertyChanging();
					this._ID_KONTRAHENTA = value;
					this.SendPropertyChanged("ID_KONTRAHENTA");
					this.OnID_KONTRAHENTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RODZAJ_DOKUMENTU", DbType="Char(3)")]
		public string RODZAJ_DOKUMENTU
		{
			get
			{
				return this._RODZAJ_DOKUMENTU;
			}
			set
			{
				if ((this._RODZAJ_DOKUMENTU != value))
				{
					this.OnRODZAJ_DOKUMENTUChanging(value);
					this.SendPropertyChanging();
					this._RODZAJ_DOKUMENTU = value;
					this.SendPropertyChanged("RODZAJ_DOKUMENTU");
					this.OnRODZAJ_DOKUMENTUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POZYCJA_DOKUMENTU_MAGAZYNOWEGO")]
	public partial class POZYCJA_DOKUMENTU_MAGAZYNOWEGO
	{
		
		private System.Nullable<decimal> _ID_DOK_MAGAZYNOWEGO;
		
		private System.Nullable<decimal> _ID_ARTYKULU;
		
		public POZYCJA_DOKUMENTU_MAGAZYNOWEGO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOK_MAGAZYNOWEGO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID_DOK_MAGAZYNOWEGO
		{
			get
			{
				return this._ID_DOK_MAGAZYNOWEGO;
			}
			set
			{
				if ((this._ID_DOK_MAGAZYNOWEGO != value))
				{
					this._ID_DOK_MAGAZYNOWEGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ARTYKULU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID_ARTYKULU
		{
			get
			{
				return this._ID_ARTYKULU;
			}
			set
			{
				if ((this._ID_ARTYKULU != value))
				{
					this._ID_ARTYKULU = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
