//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUR_Integer_WAPRO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WFMAG_DATASOURCE {
            get {
                return ((string)(this["WFMAG_DATASOURCE"]));
            }
            set {
                this["WFMAG_DATASOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WFMAG_DATABASE {
            get {
                return ((string)(this["WFMAG_DATABASE"]));
            }
            set {
                this["WFMAG_DATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WFMAG_USERNAME {
            get {
                return ((string)(this["WFMAG_USERNAME"]));
            }
            set {
                this["WFMAG_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WFMAG_PASSWORD {
            get {
                return ((string)(this["WFMAG_PASSWORD"]));
            }
            set {
                this["WFMAG_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source={0};Initial Catalog={1};Persist Security Info=True;User ID={2};Passwo" +
            "rd={3}")]
        public string WFMAG_CONNECTIONSTRING_PATTERN {
            get {
                return ((string)(this["WFMAG_CONNECTIONSTRING_PATTERN"]));
            }
            set {
                this["WFMAG_CONNECTIONSTRING_PATTERN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WFMAGConnectionString {
            get {
                return ((string)(this["WFMAGConnectionString"]));
            }
            set {
                this["WFMAGConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONTRACTORS_AUTOSORT {
            get {
                return ((bool)(this["CONTRACTORS_AUTOSORT"]));
            }
            set {
                this["CONTRACTORS_AUTOSORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ARTICLES_AUTOSORT {
            get {
                return ((bool)(this["ARTICLES_AUTOSORT"]));
            }
            set {
                this["ARTICLES_AUTOSORT"] = value;
            }
        }
    }
}
